// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: rpc_msg/rpc_msg.proto

package rpc_message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RpcMsg_SendMsg_FullMethodName = "/rpc_msg.rpc_msg/SendMsg"
)

// RpcMsgClient is the client API for RpcMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcMsgClient interface {
	SendMsg(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
}

type rpcMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcMsgClient(cc grpc.ClientConnInterface) RpcMsgClient {
	return &rpcMsgClient{cc}
}

func (c *rpcMsgClient) SendMsg(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, RpcMsg_SendMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcMsgServer is the server API for RpcMsg service.
// All implementations must embed UnimplementedRpcMsgServer
// for forward compatibility
type RpcMsgServer interface {
	SendMsg(context.Context, *SendMessageReq) (*SendMessageResp, error)
	mustEmbedUnimplementedRpcMsgServer()
}

// UnimplementedRpcMsgServer must be embedded to have forward compatible implementations.
type UnimplementedRpcMsgServer struct {
}

func (UnimplementedRpcMsgServer) SendMsg(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (UnimplementedRpcMsgServer) mustEmbedUnimplementedRpcMsgServer() {}

// UnsafeRpcMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcMsgServer will
// result in compilation errors.
type UnsafeRpcMsgServer interface {
	mustEmbedUnimplementedRpcMsgServer()
}

func RegisterRpcMsgServer(s grpc.ServiceRegistrar, srv RpcMsgServer) {
	s.RegisterService(&RpcMsg_ServiceDesc, srv)
}

func _RpcMsg_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcMsgServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcMsg_SendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcMsgServer).SendMsg(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcMsg_ServiceDesc is the grpc.ServiceDesc for RpcMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_msg.rpc_msg",
	HandlerType: (*RpcMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _RpcMsg_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_msg/rpc_msg.proto",
}
